<?php
/**
 * @copyright Copyright (c)
 *
 * @see       PROJECT_LICENSE.txt
 */

declare(strict_types = 1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Vct\ProductUpload\ViewModel\File\Request;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Request $viewModel */
$viewModel = $block->getData('view_model');
?>

<form class="form"
      action="<?= $escaper->escapeUrl($viewModel->getFormAction()) ?>"
      id="products-file-request-form"
      method="post"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $escaper->escapeHtml(__('Donwload products')) ?></span>
        </legend>

        <div class="field email required">
            <label class="label"
                   for="email">
                <span><?= $escaper->escapeHtml(__('Email/SellerId')) ?></span>
            </label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $escaper->escapeHtmlAttr(__('Email/SellerId')) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"
                       data-mage-init='{"mage/trim-input":{}}'/>
            </div>
        </div>

        <div class="field password required">
            <label class="label"
                   for="password">
                <span><?= $escaper->escapeHtml(__('Password')) ?></span>
            </label>
            <div class="control">
                <input autocomplete="off"
                       class="input-text"
                       data-validate="{required:true}"
                       id="pass"
                       name="password"
                       title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                       type="password"/>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden"
                   name="hideit"
                   id="hideit"
                   value=""/>
            <button type="submit"
                    title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>"
                    class="action submit primary">
                <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
